top_cryptocurrencies_names = ["Bitcoin", "XRP", "Ethereum", "Stellar", "Tether", "EOS", "Litecoin", "Bitcoin Cash",
                              "Bitcoin SV", "TRON", "Cardano", "Monero", "IOTA", "Binance Coin", "NEM", "Dash",
                              "Ethereum Classic", "NEO", "Zcash", "Maker", "Dogecoin", "Waves", "Tezos", "TrueUSD",
                              "USD Coin", "Bitcoin Gold", "VeChain", "OmiseGO", "Basic Attenti...", "Qtum",
                              "Paxos Standar...", "0x", "Decred", "Ontology", "Lisk", "Bitcoin Diamond", "Zilliqa",
                              "Nano", "Bytecoin", "BitShares", "DigiByte", "ICON", "Gemini Dollar", "Verge", "Siacoin",
                              "Aurora", "Aeternity", "Pundi X", "Factom", "Chainlink", "Bytom", "Steem", "QASH",
                              "Augur", "Stratis", "Revain", "Populous", "Komodo", "MaidSafeCoin", "Holo", "TenX", "Dai",
                              "Electroneum", "Golem", "Cryptonex", "Huobi Token", "Status", "Decentraland", "IOST",
                              "DEX", "Ardor", "KuCoin Shares", "Bitcoin Private", "Insight Chain", "Polymath",
                              "Elastos", "Waltonchain", "Nexo", "WAX", "Dentacoin", "STASIS EURS", "ODEM", "QuarkChain",
                              "Ark", "MobileGo", "Metaverse ETP", "HyperCash", "Wanchain", "Bancor", "Mixin",
                              "ReddCoin", "Ravencoin", "Mithril", "Aion", "THETA", "aelf", "Crypto.com", "GXChain",
                              "Digitex Futures", "PIVX"]
